### ISSUE TITLE
Background not Loading

### ISSUE THREAD

**Issue by Eppy37** [SamuiNe/Crystalline-css#14]
Running on 1.16.1

I wanted to change my background image and when I did, it stopped trying to load it and all I get now is a dark background. I tried reverting back to my old background and even the default one when you copy the code into the file and none of the backgrounds are loading onto Discord.

**Comment by SamuiNe** [comment]
Which Discord version do you use (Live / PTB / Canary), and have you tried reapplying the CSS?

**Comment by Eppy37** [comment]
I'm using the current standard version of Discord(I would assume Live). I have reapplied the CSS and I am able to make some changes that take effect immediately, suck as changing the transparency value(which in this case, just makes the black background a darker or lighter black)

**Comment by SamuiNe** [comment]
Could be due to background link not starting with `https://` or issues with it or the URL is down at the moment.
Though, it might also be due Line 48 at `.app, .connecting` background 4th value being around 1 or more than 1, but doesn't seem to be the case based on the situation.

If those two aren't the case, is it alright for me to see the screenshot and which line have you edited?

**Comment by Eppy37** [comment]
It's definitely not the above two. I've even started with a fresh install of 1.16.1 and the background images still doesn't load, No lines edited.

I've even loaded a blanks css file and then reloaded this one. The theme itself shows up fine, but the background image isn't showing up.

https://i.imgur.com/HsA1wkx.png

**Comment by Eppy37** [comment]
I did all of that and still nothing. I'm using Windows 8

the background was working perfectly fine earlier, only when I tried to change it tonight did this problem come up. I did receive like 2-3 minor discord updates since I updated to 1.16.1

**Comment by Eppy37** [comment]
Yeah, still nothing. I guess I'll just leave it alone and maybe it will fix itself through later updates/discord updates? I don't know...

For now I'll just buff up the transparency so the screen isn't so dark. the rest of the theme is still fine.

**Comment by shinji257** [comment]
Try clearing your discord cache.  You will want to exit discord before doing this but then (on Windows) go to %appdata%\discord and remove the Cache and GPUCache folders.  Start discord and it should pull new resources automatically.

Other platforms will likely have it in related locations on those systems.

**Comment by Eppy37** [comment]
Did that. Still no background.

**Comment by SamuiNe** [comment]
Kind of curious, what does your `.app, .connecting` look like?

**Comment by Eppy37** [comment]
https://i.imgur.com/KEbDmYP.png

It should all be default except for the Opacity value which I brought down to 0.6 so it isn't so dark.

**Comment by SamuiNe** [comment]
Yeah, Beautifuldiscord tends to be wonky at times. Also my apologies for the late response, and I'll keep a note for future troubleshooting. Thank you very much, eppy!
