### ISSUE TITLE
server list in discord not transparent

### ISSUE THREAD

**Issue by DoYouPikachu** [SamuiNe/Crystalline-css#17]
![2018-07-31_16-55-18](https://user-images.githubusercontent.com/16530766/43493402-c00e244c-94e2-11e8-8150-95096db11895.png)
This should be self explanatory. I'm disappointed.

Just kidding ily for this theme it's still fricking amazing and you're doing a great job updating it.

**Comment by SamuiNe** [comment]
Thank you very much, DoYouPikachu!

It should be fixed at the latest version.
