### ISSUE TITLE
Better Discord theme file

### ISSUE THREAD

**Issue by shinji257** [SamuiNe/Crystalline-css#3]
I know this theme is designed for use in Beautiful Discord, however, I found it works fine in Better Discord as well.  I made up a quick theme file that imports in the css from here (so I get your updates) and also has a small body segment meant to provide a way to override both the background as well as the background size.  If you want I can post it otherwise feel free to close this report if you don't.

**Comment by marsha-222** [comment]
I’m trying to use this theme on my discord app. How can I do that?

**Comment by SamuiNe** [comment]
@marsha-222 You'll need to have Python 3.4+ added to PATH and have [BeautifulDiscord](https://github.com/leovoel/BeautifulDiscord) installed first in order to use the theme. Then you need to enter `beautifuldiscord --css CSS_filepath_here` at the command prompt to set the theme.

**Comment by SamuiNe** [comment]
@shinji257 after considering it for quite a while, I think it is fine. 
Feel free to do a pull request with the theme file, though having it seperate with the crystalline.css, in a folder labeled BeautifulDiscord, and a guide how to setup the file would be nice. Thank you in advance!

**Comment by SamuiNe** [comment]
Done merging pull request #6 , closing the issue now~
